#!/bin/sh

TMP=$HOME/work/gofish

VERSION=`fgrep Version: gofish.spec | cut -d' ' -f2`
RELEASE=3

ARCH=`uname -m`
case $ARCH in i*86) ARCH=i386;; esac

PKG=gofish-$VERSION-$ARCH-$RELEASE.tgz

echo "Creating $PKG"

rm -rf $TMP
mkdir -p $TMP || { echo "mkdir $TMP failed"; exit 1; }

./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	--with-gopheruser=nobody

make || { echo "Make failed"; exit 1; }

make install DESTDIR=$TMP || { echo "Install failed"; exit 1; }

gzip $TMP/usr/man/man1/*
gzip $TMP/usr/man/man5/*

mkdir $TMP/install
install slackware/doinst.sh $TMP/install
install -m 644 slackware/slack-desc $TMP/install

cd $TMP

# Change some file names
mv etc/gofish.conf etc/gofish.conf.default
mv etc/gofish-www.conf etc/gofish-www.conf.default
mv var/gopher var/gopher.new

makepkg -l y -c y $PKG
